### ISSUE TITLE
chop off my branch

### ISSUE THREAD

**Issue by cward5** [mcarth3/cs470#8]
Is there a way to just get rid of my branch? It's just messed up, and trying to merge 'master' into it didn't restore the deleted files like I'd hoped it would, whereas if I were to merge it into master, the files would be deleted. So let's just chop that branch off and start from scratch, I hadn't done anything meaningful anyways that would be lost.

**Comment by obritton** [comment]
You probably want to stash what you have.
Then do a fresh checkout of master.
Then create a new branch.​

On Wed, May 11, 2016 at 3:35 PM, cward5 notifications@github.com wrote:

> ing meaningful anyways that would be l

Thanks,
Tari
(801) 319-5477

**Comment by cward5** [comment]
That would be great if I could do a fresh clone of master. But I've tried three times now, and it keeps getting stuck after the first 20 or so files that go into the .git folder. I really hope I didn't manage to screw up the whole repository....

**Comment by obritton** [comment]
We can just revert to emailing the one file we care about around.
Especially since we've yet to edit it simultaneously.

Looks like I'm done for the day. Wed is my tight day. I'm busy until 10am,
and then I'm booked from 5:30p to midnight, and I have to go home and
shower before I start in on the rest of my day.

I'm stuck in C# not managing a collection correctly for A*. That bug
shouldn't persist across languages. I'll come in early tomorrow and commit
it to python and see what we get! Then I'll see about adding some sweet
graphics for the +20%. If RRT is done, we can write this up and move on to
lab 3!

On Wed, May 11, 2016 at 3:59 PM, cward5 notifications@github.com wrote:

> ps getting stuck after the first 20 or so files that go in

Thanks,
Tari
(801) 319-5477

**Comment by cward5** [comment]
Looks like it may have just been struggling with how large it is overall. I'm cloning it using github's client instead of SourceTree, so I've got a progress readout of how many of the 3000+ files have come through.
